drop table blog if exists;

create table blog(id IDENTITY, title varchar(100),dates date, content longvarchar(20000), link varchar(500));

insert into blog(title, dates, content, link) values('Walk for Wellness','2014-06-14','It is the umpteenth time I put on my sweatpants and T-shirt, all set for my morning walk. Every day is a new day as I look forward to my tryst with nature. I find myself reaching for my walking shoes with a childlike joy. This habit of mine started as leisure strolls in the neighborhood with my 2 year old strapped in a stroller. That was some 15 years ago. Since then I have been on a roll, thanks to my walking partners - friends, and family and above all love for nature.It is sad that people are so caught up in the daily rut they forget to acknowledge simple gifts of life. More and more people are walking away from nature than walking in it. Studies have proved that walking outdoors is a big stress-buster. Thirty minutes of daily walk is said to have immense effect on people�s stress and increases their productivity.',
'http://www.prevention.com/fitness/fitness-tips/14-walking-workouts-burn-fat-and-boost-energy');
insert into blog(title, dates, content, link) values('Green Tea','2014-05-10','If memory serves me right, I took the first sip of green tea about 7 years back at my friend�s house, and it stayed with me as a habit since then. In the earlier days, I made a conscious effort to have it as part of my daily routine, especially in winters. This practice of mine ensued from the awareness of numerous health benefits from all kinds of media, that this simple drink had to
offer. I also realized not too late that you really don�t care about the benefits or the glorified stories of any food when it is part of your life, like your family members. I am glad to notice that it has taken a place in the hearts of my 17-year old as well as my husband. I for one, savor green tea not for any  specific intent, but for its refreshing aroma and earthy tone. It connects me to the basics, and reminds me where I come from.  It has an unassuming quality with only goodness to offer.  I also like green tea for the fact that it is light in the stomach, almost like water.Green tea is simple to make. Fill three-fourth of a kettle with water. Bring the water to a boil. Switch off the flame. Add 2 teaspoons of green tea leaves or couple of tea bags, and let it steep for about 5 minutes. And voila, it is ready! Pour it in a cup and drink warm. One kettle would suffice for an entire day. It can be consumed just as is or with honey and lemon if you want added taste. If you like it cold, add ice cubes. I like mine simple and warm.
Green tea comes in all kinds of flavors, from just plain to simple lemon to a combination of fruit and flower flavors with exotic names! You can find a wide variety of them at most superstores,  covering an entire spectrum of texture, flavor and price; it is an empire in its own right!On this cold winter day, I am at the beckoning of this warm and soothing beverage sitting on my kitchen counter!  Next time you are offered a cup of green tea, see if you reach for it with a gleam in your eyes.','www.soulkuest.wordpress.com');
insert into blog(title, dates, content, link) values('Optimism',
                                                    '2014-04-28',
                                                    'It is not what happens to you in life , but your attitude towards what happens that matters!
This saying comes to mind when I see pessimistic people blaming their bad luck that for some reason finds a way into their lives at every beck and call. Why is it that some people are more inclined to think negative than being optimistic.
Is it easy to cultivate a positive outlook in life?  Is it nature or nurture or both? Well, I think both. As with any trait, we can certainly condition our mind to think positive and take responsibility of our actions and situations and move on without playing the blame game.
Optimism, by itself is a passive quality that cannot come into fruition unless coupled with result-yielding qualities like hard work, perseverance and determination.
It is a catalyst that adds to the quality of any endeavor you undertake. The usage of this word seems very clich�d, but one doesn�t realize the power in approaching anything in life with a sense of boundless energy created in positive light. 
Look at it this way, what has to happen and what will happen is not going to change by the way you react to it. So, why not cultivate the habit of being in a state of mind that is more congenial to your well-being. 
Yes, believe it or not, it is the way we think, more often than not, that can doom or save our life, rather than the real situation we are in.
We often give things a negative connotation or a distorted image due to our unrealistic expectations of how things should work from the framework of fairness set by us. 
And we brood and we grumble on how things have not worked as planned and spread a wave of dissatisfaction and pessimism that further hamper our chances on future accomplishments. 
The vicious cycle continues and the victim is in the whirlpool of constant anger and discontent.',
'http://soulkuest.wordpress.com/category/look-inside/optimism-look-inside/');

insert into blog(title, dates, content, link) values('Missing shoe','2014-04-15','As I sped past the usually commuted highway for the 1000th time, I noticed something that was out of the ordinary. A shoe on the curbside cast away, forlorn, neglected. Just a single shoe without its pair.
 The sight brought a sudden knot to my throat as thoughts not very pleasant crossed my mind. 
Could it have been from an accident where the shoe of the victim was thrown mercilessly off its owner, or could it be that it flew off from behind a speeding truck where memories are packed as part of a moving venture, or may be a lonesome side-walker had to desert it in an attempt to run away from a predator.
 Whatever it was, the sight of the lonely shoe brought eerie and discomforting thoughts.','http://soulkuest.wordpress.com/category/the-shoe/');
 insert into blog(title, dates, content, link) values('Ordinary is Extraordinary','2014-05-02','The other day, while driving down the familiar road to drop off my daughter at her school, I noticed the joggers and walkers I usually see in the mornings pass by, and something in me reminded that �Everything is Alright�. Many of them, I know only by face and some I have personally known for years, but they all contribute to the sense of rhythm, that things are going on just the way they should be! Isn�t it queer that we all pass through hundreds of these moments everyday, still seem unaware of them and take them for granted?! These are, in fact the spokes of the wheel  we call LIFE. When I pay no attention, all things of true value go uncelebrated, like cherish my great childhood, relish the bitter sweetness of motherhood or enjoy the journey of womanhood.','http://soulkuest.wordpress.com/category/everything-is-alright/');

insert into blog(title,dates,content, link) values('Calluses','2014-03-12','The souls who have experienced the pain to become only stronger, are souls of steel. They are the ones who make a difference. The ones who give in and create wounds that never heal only help spread the wave of discontent and disgruntlement and a sense of sheer insecurity not only in themselves, but to others around them. While lot of the healing has to do with the intensity of the experience one goes through or the repeated occurrence of these unpleasant events that render them helpless to stand on their own, any amount of empowerment has to start from within first. Any amount of external help is in vain, until the internal has the realization.
The times I felt dejected and blamed the situation,  I reminded myself of the hapless many around me in much worse conditions that needed more tending and nurturing. That in itself was healing enough. The times I have fallen to pieces in the past have only taught me to get right back up, and wield the bruises for a higher purpose. When I recouped and put the pieces together for the thousandth time, I smiled at the calluses caused from my healed wounds . It is only but fact that most of the pain we feel, is carried within us for an unnecessarily longer period of time, rendering us chronic whiners and depressed souls. They need to be put behind, for you have the sole power to do so. No one else can tread the path for you; the journey is solely yours to endure.
Wouldn�t you agree that there is a sense of sweet conquer when you stand upright at the face of unforeseen and difficult circumstances, be it the loss of a loved one, or abuse at the hands of supposedly loved ones, separation due to natural or unnatural means, or just sheer lack of nurturing. This alone is enough to make you a matured soul, sensitive towards others pain, touch and be touched by others. The calluses remind you of the victorious journey traversed to make you a far stronger individual at heart, yet vulnerable to make a change. Let there be calluses, not sores that succumb to the infliction and turn to wounds that stay raw and never choose to heal. Let the disappointments and adversities build a fort of sheer will power to conquer all negativity and race right through into the arms of possibilities and hope. Let us take charge and act from the unfavorable experiences in the past and turn them into the best we could strive for in the future than crumbling and dissolving to oblivion.',
'http://soulkuest.wordpress.com/category/calluses/');


drop table bloguser if exists;

CREATE TABLE PUBLIC.BLOGUSER (
	ID INTEGER NOT NULL,
	USERNAME VARCHAR(100),
	PASSWORD VARCHAR(100),
	CONSTRAINT SYS_PK_10104 PRIMARY KEY (ID)
);

INSERT INTO BlogUSER VALUES(0,'Blogorama','enterblog');

